### ISSUE TITLE
[BUG]: Crash when connecting power cable to Railcraft Steam Engine

### ISSUE THREAD

**Issue by xJon** [Thorfusion/Mekanism-Community-Edition#103]
### Describe the bug

As the title describes (first reported over https://github.com/xJon/The-1.12.2-Pack/issues/856).

### Mekanism Version

`9.8.3.390`

### Railcraft Version

`12.1.0-beta-8`

### Minecraft Version is this regarding?

`1.12.2`

### The crash report in folder ./crash-reports (both server and client logs)

https://mclo.gs/HqkUQRY

**Comment by maggi373** [comment]
same npe as in #109

**Comment by maggi373** [comment]
unable to reproduce the issue, however added an nullcheck that might fix it
