### ISSUE TITLE
[ENHANCEMENT]: Control Circuit recipe softlocking progression

### ISSUE THREAD

**Issue by Desempregago** [Thorfusion/Mekanism-Community-Edition#105]
### Is your enhancement request related to a problem? Please describe.

With the Control Circuit requiring Silicon, you keep the player unable to progress, since the ONLY machine that's able to create silicon also REQUIRES it, making you rely on external sources.

### Describe the solution you'd like

Readd the old Circuit recipe via config or change the Crusher recipe to require something else, like Enriched Alloys

### Minecraft Version is this regarding?

1.7.10

**Comment by Desempregago** [comment]
Nevermind, there's a config option already.

**Comment by maggi373** [comment]
hahahaha, not enough testing from my side, this depends on what silicon mod you added.

**Comment by Desempregago** [comment]
Couldn't you just add your version of Silicon in Mekanism CE?

**Comment by maggi373** [comment]
its there for modpack creators, and the dev time isnt worth it to add silicon, feel free to pr if you want to.
