### ISSUE TITLE
Some ideas.

### ISSUE THREAD

**Issue by rguy98** [Thorfusion/Mekanism-Community-Edition#114]
1) Ultimate Tier factory machines.

2) Factory versions of other machines with item-based inputs (e.g. Sawmill, Chemical Oxidizer, PRC)

3) Fluid version of the Digital Miner

4) Cable covers, similar to AE2's facades

5) Multiblock gas tank, similar to the Dynamic tank.

**Comment by maggi373** [comment]
wrong repo mate, please go to https://github.com/Thorfusion/Mekanism-Community-Edition/issues to submit your issue

**Comment by BaccarWozat** [comment]
Seconded about sawmill factories. I got used to mine for 1.12/etc. so the 1.7 one is sorely needed.

**Comment by maggi373** [comment]
oh, theres an factory in 1.12.2, hmm will look on it later today

**Comment by maggi373** [comment]
already made the texture for 1.12 :(
