### ISSUE TITLE
Wrong CurseForge dependencies for 1.12.2-9.12.5

### ISSUE THREAD

**Issue by R93950X** [Thorfusion/Mekanism-Community-Edition#115]
Upon installing the first MEK CE for 1.12.2 after the merge CodeChickenCore and Forge Multi Part for 1.7.10 are installed alongside it. Unsurprisingly this causes a crash.

**Comment by maggi373** [comment]
i fixed this within the hour from upload i believe, gonna check when home in 8 hours

**Comment by maggi373** [comment]
should be already fixed from what i can see in the browser...

**Comment by R93950X** [comment]
Seems like we're waiting on CurseForge to recognize the change in the client? I found the issue by installing the new version in a fresh instance after updating the mod caused issues in my main pack.

**Comment by maggi373** [comment]
probably, will check when im home

**Comment by maggi373** [comment]
so curseforge has its bugs i see. i have added an incompatible dep on the affected deps that gets added, i removed the deps on the alpha builds aswell if it used the last mod added. and the changelog it is showing is also wrong so thats that. BUT it is working properly now

**Comment by saovenn** [comment]
issue still persits in the newest version



https://github.com/Thorfusion/Mekanism-Community-Edition/assets/44532103/79ba7a6a-7589-488d-9c90-c2ba6b441a5c

**Comment by maggi373** [comment]
> issue still persits in the newest version
> 
>  CurseForge_DG84lC7qiV.mp4

fixed, i need to set those as forced on 1.7.10 and curse sets them as defaults when i update, 9.12.7 didnt have the issue tho. aslo curse stupid

**Comment by saovenn** [comment]
The problem occurs again in the latest version

Forge Multi Part / CoreChickenCore (1.7.10 and 1.12.2) are installed simultaneously

**Comment by maggi373** [comment]
> The problem occurs again in the latest version
> 
> Forge Multi Part / CoreChickenCore (1.7.10 and 1.12.2) are installed simultaneously

Yea, i have no idea whats happening, the latest update that got pushed today have no dep on it. so hopefully this fixes it
