### ISSUE TITLE
[BUG]: Rendering crash with Mariculture Infinity Water bucket placed in Evaporation Controller

### ISSUE THREAD

**Issue by AstroTibs** [Thorfusion/Mekanism-Community-Edition#117]
### Describe the bug

Someone on my server had placed a Mariculture Infinity Water bucket into the inlet in his Thermal Evaporation Controller to help him get water quicker. It seemed to work.

However, when he teleported away from his compound and returned later, his client crashed. In addition, his entire game was rendering with a red tint.

I think it has something to do with the multiblock re-forming when he re-enters and loads the chunk, and the red particles that appear. Why this happens and why the bucket would be responsible, I don't know.

The coordinate in the crash report is the coordinate of his controller. He has two adjacent towers, and this one is the one containing the bucket.

For full disclosure: we are both using OptiFine and FastCraft.

### To Reproduce

1. Create a compiled evaporation tower
2. Place an Infinity Water into the controller's inlet slot
3. Leave the chunk so that it unloads
4. Return to the chunk and have it re-load and recompile the tower
5. Enjoy being marooned

Unknown if OptiFine causes or assists in this issue.

### Expected behavior

No rendering crash from the tower compiling.

### Mekanism Version

9.10.28

### Minecraft Version is this regarding?

1.7.10

### What OS are you seeing the problem on?

Windows

### Name of modpack if applicable

Galaxy Odyssey

### Version of said modpack if applicable

Any version past 2.31.23.1 uses that Mekanism version

### Screenshots

![marooned](https://github.com/Thorfusion/Mekanism-Community-Edition/assets/29684118/3ad3cf19-8245-4691-a76e-ee45b416c502)

### The crash report in folder ./crash-reports (both server and client logs)

```shell
[crash-2023-05-13_00.20.49-client.txt](https://github.com/Thorfusion/Mekanism-Community-Edition/files/11469153/crash-2023-05-13_00.20.49-client.txt)
```

**Comment by maggi373** [comment]
hi, you are running mek with "modern" mods ie coretweaks, archaictweaks, flying cullers,  and so on. which is fine but these mods do have behavior we cant predict. i recommend checking their configs and disabling the mods as of worst case. i know that some configs / mods dont work well with mek nor defencetech when going out of chunk range. unfortunately i dont remember what i did in my pack to fix this.

**Comment by maggi373** [comment]
can i get a world save to test with? if the server still has the bug on it, we can join and test aswell

**Comment by maggi373** [comment]
i got blue tint, beat that!
