### ISSUE TITLE
[BUG]: Looking at machines cause secere lags.

### ISSUE THREAD

**Issue by YiRanMushroom** [Thorfusion/Mekanism-Community-Edition#145]
### Describe the bug

Looking at machines cause secere lags.

### To Reproduce

Look at a machine, and use /forge tps.
It is actually existing, not only the data.

Please see this video.

https://www.youtube.com/watch?v=TuDQ6ytJPgc

Some times the tps would drop to less than 5/s.

### Expected behavior

tps won't drop

### Mekanism Version

Newest with Mekanism Generators

### Minecraft Version is this regarding?

1.7.10

### The crash report in folder ./crash-reports (both server and client logs)

```shell
No crash
```

**Comment by YiRanMushroom** [comment]
[2023-10-09-7.log](https://github.com/Thorfusion/Mekanism-Community-Edition/files/12852620/2023-10-09-7.log)
here is the log

**Comment by YiRanMushroom** [comment]
Also found this problem in vanilla mekanism, so it's probably the fault of them

**Comment by YiRanMushroom** [comment]
not the problem of mekanism

**Comment by maggi373** [comment]
please post the fix you found for your issue, for people that might have the same issue.

**Comment by YiRanMushroom** [comment]
This is because of a mod about the GTEU and RF convertion,  and cause by that mod failed to get some property of mekanism machines, also have something with hwyla. So basically I don't know how to fix, I just changed to TOP and that works fine.
