### ISSUE TITLE
[ENHANCEMENT]: ability to disable blocks and items in config

### ISSUE THREAD

**Issue by ghost** [Thorfusion/Mekanism-Community-Edition#147]
### Is your enhancement request related to a problem? Please describe.

there's no way to disable blocks and items

### Describe the solution you'd like

add ability to disable blocks and items from registring

### Minecraft Version is this regarding?

1.7.10

**Comment by ghost** [comment]
+ ore generation for salt, osmium, tin and copper

**Comment by maggi373** [comment]
mek is modular with the core/tools/generator modules. you can disable the recipes for everything in the new config that mek:ce has and ore generation can already be disabled as its an native feature for mek.
