### ISSUE TITLE
[BUG]: Mekanism windmills are more powerful at lower y levels instead of higher y levels.

### ISSUE THREAD

**Issue by AT-L4S** [Thorfusion/Mekanism-Community-Edition#150]
### Describe the bug

Mekanism windmills are more powerful at lower y levels instead of higher y levels.
Tested on Enigmatica 2 Expert: Extended modpack w/ superflat world.

### To Reproduce

1. Set up a Mekanism windmill at y=10 and y=200 with a EnderIO conduit leading into an energy trash.
2. Use the EnderIO conduit probe to see how much RF/t is going through it.
3. The one at y=10 generates more than the one at y=200.

### Expected behavior

The one at y=200 should generate more than the one at y=10

### Mekanism Version

9.12.8

### Minecraft Version is this regarding?

1.12.2

### What OS are you seeing the problem on?

MAC

### Name of modpack if applicable

Enigmatica2Expert: Extended

### Version of said modpack if applicable

1.26

### The crash report in folder ./crash-reports (both server and client logs)

```shell
Did not crash.
```

**Comment by sddsd2332** [comment]
Let me see
Maybe the author of e2ee wrote it backwards [here](https://github.com/Krutoy242/Enigmatica2Expert-Extended/blob/master/config/mekanism/MekanismGenerators.cfg#L41-L51), turning [WindGenerationMax](https://github.com/Krutoy242/Enigmatica2Expert-Extended/blob/master/config/mekanism/MekanismGenerators.cfg#L42) and [WindGenerationMin](https://github.com/Krutoy242/Enigmatica2Expert-Extended/blob/master/config/mekanism/MekanismGenerators.cfg#L48) upside down

**Comment by maggi373** [comment]
> Let me see Maybe the author of e2ee wrote it backwards [here](https://github.com/Krutoy242/Enigmatica2Expert-Extended/blob/master/config/mekanism/MekanismGenerators.cfg#L41-L51), turning [WindGenerationMax](https://github.com/Krutoy242/Enigmatica2Expert-Extended/blob/master/config/mekanism/MekanismGenerators.cfg#L42) and [WindGenerationMin](https://github.com/Krutoy242/Enigmatica2Expert-Extended/blob/master/config/mekanism/MekanismGenerators.cfg#L48) upside down

hahaha, amazing, thx for the help.
