### ISSUE TITLE
[BUG ULTIMATE]: Um craft é susbstituido pelo mod "Galacticraft"

### ISSUE THREAD

**Issue by samuel509** [Thorfusion/Mekanism-Community-Edition#153]
### Describe the bug

Por algum motivo o item "Circuito Basico" está usando uma receita alternativa como craft, bem, basicamente ele deveria ser feito com a barra de ósmio (Até onde eu sei) e o item que está no lugar é o silicone bruto, que para obter precisa criar uma maquina (A maquina usa circuito basico para ser feita, basicamente é impossivel de fazer) . Tentei remover a receita alterada do CraftTweaker porem nada deu certo (Eu provavelmente não sei usar isso).

### To Reproduce

Vou deixar assim mesmo pois o erro está na receita e não em algo feito por mim diretamente.

### Expected behavior

O esperado era que o craft original fosse mantido, o unico craft que notei com esse problema é o do circuito basico

### Mekanism Version

9.10.33

### Minecraft Version is this regarding?

1.7.10

### Name of modpack if applicable

N/A

### Version of said modpack if applicable

?

### Screenshots

![image](https://github.com/Thorfusion/Mekanism-Community-Edition/assets/70274633/d999f7ac-05f5-4b88-8f2a-8ad5736e1582)

### The crash report in folder ./crash-reports (both server and client logs)

```shell
Não ouve crash ou algo semelhante.
```

**Comment by maggi373** [comment]
please write in english. anyway, go to the config files and deactivate silicon compat, as this is an feature added to mek:ce.

**Comment by samuel509** [comment]
Worked, thx man
