### ISSUE TITLE
[BUG]: Tank capacity/rate config options no longer exist

### ISSUE THREAD

**Issue by AstroTibs** [Thorfusion/Mekanism-Community-Edition#155]
### Is your enhancement request related to a problem? Please describe.

I recently discovered that values for things like fluid/gas tank, bin, etc. are no longer accessible in the configs.

### Describe the solution you'd like

I'd like a return to being able to set the storage capacities of things like Bins, Fluid Tanks, and Gas Tanks in the config. Values such as the Basic Fluid Tank being able to hold 14 buckets seems both arbitrary and too high.

### Describe alternatives you've considered

Currently my only alternative is to roll back to pre-CE Mekanism, but losing all the new features and fixes would be worse.

### Minecraft Version is this regarding?

1.7.10

### Additional context

I had values such as storage configured for the pre-CE version of Mekanism to suit my modpack. Recently it was brought to my attention that the tanks are severely overpowered with respect to other tanks in the pack, which didn't use to be the case.

I personally did not manipulate other config values like pull speed, but I imagine other players might like to have access to that again.

**Comment by maggi373** [comment]
its still available far as i know, checked your config?

**Comment by maggi373** [comment]
https://github.com/Thorfusion/Mekanism-Community-Edition/wiki/Configuration-9.10.27-to-CURRENT

**Comment by AstroTibs** [comment]
Yes, I actually wiped the configs to generate them fresh to see.
No such config values exist in any of the files in the `config/mekanism/` folder. Nor does the word "storage."
The word "tank" only exists for turning them on/off or having pre-filled tanks enabled.

Here's the `Mekanism.cfg` file:
https://pastebin.com/W7DaimkP

And the `MekanismGenerators.cfg`, which has values for generators, but not storage, as you'd expect:
https://pastebin.com/r2HxCcEt

**Comment by maggi373** [comment]
oh shit

**Comment by maggi373** [comment]
i'm unable to debug with your pack as its broken with stuff, aka modirector which doesnt even work. it will take some time to debug as i need to setup smth instead

**Comment by maggi373** [comment]
if you want to speed it up test 9.10.17 and 9.10.26 as they also have some config changes and see if tier catogory appears. gonna go to bed

**Comment by AstroTibs** [comment]
ModDirector is a little shaky, but I find that sometimes it works if you close the popup window.

Alternately, if you delete ModDirector entirely after downloading but before launching the pack, that should be okay. MD is **only** used for resourcepacks.

**Comment by AstroTibs** [comment]
**9.10.26** and **9.10.27:** The options exist and work as expected.

**Edit:**
The last version it worked in is **9.10.31**.
This issue first appeared in **9.10.32**.

**Comment by maggi373** [comment]
27 was the last version in my pack before i stopped playin modded mc. so kinda explains that it atleast works there as i probably would have notoced it. if you really want to you can find the version where it breaks or wait day for me to get back

**Comment by AstroTibs** [comment]
I just updated my comment. It first broke in **9.10.32**.

**Comment by maggi373** [comment]
> I just updated my comment. It first broke in **9.10.32**.

i was not expecting that release to break it, but i might see the issue

**Comment by maggi373** [comment]
i have found the issue, still at work so a fix will come later

**Comment by maggi373** [comment]
@AstroTibs please review this dev version https://maven.thorfusion.com/artifactory/dev/mekanism/Mekanism-Community-Edition/1.7.10-9.10.33-419/Mekanism-Community-Edition-1.7.10-9.10.33-419-ALL.jar

**Comment by AstroTibs** [comment]
That dev version seems to have solve the issue.
I didn't check literally every possibility but I saw e.g. `BasicFluidTankStorage` was there at 14000, and I was able to change that value and see it reflected in the game.

**Comment by maggi373** [comment]
> That dev version seems to have solve the issue. I didn't check literally every possibility but I saw e.g. `BasicFluidTankStorage` was there at 14000, and I was able to change that value and see it reflected in the game.

updatin
