### ISSUE TITLE
There are some incorrect (outdated)  lang in zh_CN files

### ISSUE THREAD

**Issue by NealDeal34** [Thorfusion/Mekanism-Community-Edition#160]
### Describe the bug

With the updates of this mod， some item path(in lang)were No longer matching，can you replace it with the correct file（I can provide the file but I can't crate a pull request directly，The Modified file has been attached，you can check it easily），please
[zh_CN.txt](https://github.com/Thorfusion/Mekanism-Community-Edition/files/14189867/zh_CN.txt)

### To Reproduce

the lang's item paths were incorrect，eg.the “item.basicFactoryInstaller.name”should be “item.basicTierInstaller.name” and so that some translation can't work as well

### Expected behavior

can you replace zh_CN.lang with the correct version，please，thank you very much
[zh_CN.txt](https://github.com/Thorfusion/Mekanism-Community-Edition/files/14189929/zh_CN.txt)

### Mekanism Version

9.10.35

### Minecraft Version is this regarding?

1.7.10

### The crash report in folder ./crash-reports (both server and client logs)

```shell
none
```

**Comment by maggi373** [comment]
hi, can you explain you could't make an pull request as that is the proper way to do this :)
its ok if you can't aswell, just want to know if there is an issue on this repo.

**Comment by Omgise** [comment]
@maggi373  I can help :)

**Comment by NealDeal34** [comment]
> hi, can you explain you could't make an pull request as that is the proper way to do this :) its ok if you can't aswell, just want to know if there is an issue on this repo.

I am sorry that I took so long to respond，and It's all my personal fault.in one word,I'm a greenhand for this and need to learn a lot,but i'm eager to make a contribution and bother you in a hurry,i feel It's kind of jerk now，sorry about that sincerely and thank you very much for everything you did，again @maggi373 @Omgise
