### ISSUE TITLE
[ENHANCEMENT]: Add config file for atomic disassembler

### ISSUE THREAD

**Issue by moob212** [Thorfusion/Mekanism-Community-Edition#165]
### Is your enhancement request related to a problem? Please describe.

Atomic disassembler is relatively easy to get, but it's too overpowered

### Describe the solution you'd like

Add config file for atomic disassembler. There should be possible to change damage and mining speed

### Minecraft Version is this regarding?

1.7.10

**Comment by maggi373** [comment]
fixed by #179
