### ISSUE TITLE
[ENHANCEMENT]: Electric Bow shooting animation

### ISSUE THREAD

**Issue by RuiXuqi** [Thorfusion/Mekanism-Community-Edition#169]
### Is your enhancement request related to a problem? Please describe.

Electric Bow has no shooting animations
Mekanism team didn't make the anim until 1.15

### Describe the solution you'd like

https://github.com/mekanism/Mekanism/issues/5523

### Minecraft Version is this regarding?

1.12.2

### Additional context

I have tried to port the models files, but they didn't work. I think it may because the old V9 code doesn't have the predicates they need
Also, it is a good idea to add the encoded texture for Configuration Card, which is added in https://github.com/mekanism/Mekanism/commit/9f6c6da3c2631d332419f406f31844e2ded8cdfd

**Comment by maggi373** [comment]
fixed by #170
