### ISSUE TITLE
[ENHANCEMENT]: Possible Config to adjust the Fusion reactor Power / Steam output

### ISSUE THREAD

**Issue by JynxVer** [Thorfusion/Mekanism-Community-Edition#182]
### Is your enhancement request related to a problem? Please describe.

Not an issue, just wondering if some configurability for the Fusion reactor could be added

### Describe the solution you'd like

Could you guys add a config to edit the Fusion Reactors' RF and Steam output?

The nerf you guys did was more than deserved, but it's very harsh and it'd be amazing to have some customizability on the reactor as the current numbers are quite low and make balancing around other mods difficult, similarly to when they were extremely high 

### Minecraft Version is this regarding?

1.7.10

**Comment by DrParadox7** [comment]
I'll see what I can do

**Comment by SpoilersMC** [comment]
I've already got this implemented in dev I was just making sure it works before submitting it, I can get it out in a few hours
