### ISSUE TITLE
[BUG]: Chemical crystalizer is not accepting clean slurries

### ISSUE THREAD

**Issue by LeoArtefacts** [Thorfusion/Mekanism-Community-Edition#183]
### Describe the bug

The crystalizer is not accepting clean slurries to produce crystals of a given resource

### To Reproduce

1. Place down the automation to make the slurry
2. Try putting the slurry into the chemical crystalizer with either the gas tank or pressurized cables

### Expected behavior

The chemical crystalizer should accept the clean slurries to make crystals

### Mekanism Version

9.12.10

### Minecraft Version is this regarding?

1.12.2

### What OS are you seeing the problem on?

Windows

### Name of modpack if applicable

Enigmatica 2: Expert Extended

### Version of said modpack if applicable

1.44.0

### Screenshots

![2024-09-27_21 23 07](https://github.com/user-attachments/assets/6cd8827c-f2fb-4c7d-a3c0-f07f0f512aad)

### The crash report in folder ./crash-reports (both server and client logs)

```shell
https://paste.atlauncher.com/view/05683916-2d23-4a9f-83db-64344a6a7d10


(this is not a crash, but above is the full log file of my client)
```

### Please provide the following other files

https://gist.github.com/FrenziedDeath/ebf4883e99f87a26e2f08f14c4b451ea

[latest.log](https://github.com/user-attachments/files/17168933/latest.log)

**Comment by LeoArtefacts** [comment]
Now it suddenly started working again when putting in the gas tanks directly. However, it still isn't accepted through the pressurized pipes.
![2024-09-27_21 50 44](https://github.com/user-attachments/assets/9fc659d7-a7d4-4a19-b30c-26e46a03d66b)
![2024-09-27_21 50 48](https://github.com/user-attachments/assets/32c64557-424e-4968-b962-d6ff1b4447f3)
![2024-09-27_21 50 50](https://github.com/user-attachments/assets/5785b787-2792-484d-97b0-b456435b615f)
![2024-09-27_21 50 55](https://github.com/user-attachments/assets/1d2b5d45-87f2-4523-a9f7-8b6aa0174139)
![2024-09-27_21 51 00](https://github.com/user-attachments/assets/97e3eb84-f0cc-4818-8cb0-a1c9b1d8e354)

**Comment by maggi373** [comment]
Hi, thanks for the detailed report, did you by mistake introduced another liquid, like being 10ml left? anyway, will look into this further tommorrow.

**Comment by LeoArtefacts** [comment]
Well, it doesn't seem like to me. 

![2024-09-27_22 09 48](https://github.com/user-attachments/assets/1d9cdc19-2bda-4101-8183-032613407abf)

**Comment by LeoArtefacts** [comment]
Now it just... suddenly seems to be working again. It's like this issue keeps coming and disappearing. Will reopen if the issue reappears.
