### ISSUE TITLE
[ENHANCEMENT]: Mek crashes with 2.7.0-beta2

### ISSUE THREAD

**Issue by chixiguaya** [Thorfusion/Mekanism-Community-Edition#184]
### Describe the bug

I have joined in gtnh 2.5.1 without any problems, but in the latest version of 2.7.0-beta2, the game will not start.
I guess it might be a problem with codechickencore.In 2.5.1, it has not yet merged with codechickenlib.

### To Reproduce

1.Install the latest version of GTNH
2.Add mek-ce

### Expected behavior

Able to launch and enter the world

### Mekanism Version

9.10.37

### Minecraft Version is this regarding?

1.7.10

### What OS are you seeing the problem on?

Windows

### Name of modpack if applicable

GTNH

### Version of said modpack if applicable

2.7.0-beta2_JAVA17-21

### Screenshots

![image](https://github.com/user-attachments/assets/66d9a580-86b3-4ddc-a7b3-caad6b9df2a2)

### The crash report in folder ./crash-reports (both server and client logs)

```shell
no report
```

### Please provide the following other files

[fml-client-latest.log](https://github.com/user-attachments/files/17265469/fml-client-latest.log)

**Comment by maggi373** [comment]
you seems to have uploaded the wrong log, however this issue seems to be with [lwjgl3ify](https://github.com/GTNewHorizons/lwjgl3ify) . the issue is at our end and we'll add support for it soon.

**Comment by maggi373** [comment]
mekanism works with gtnh 2.6.1 and its not probably [lwjgl3ify](https://github.com/GTNewHorizons/lwjgl3ify) as other users have tested it with latest version. its an beta build, so we will look into it further when 2.7.0 releases

**Comment by DrParadox7** [comment]
Nothing in that stacktrace references Mekanism and that user is using a heavily modified version of GTNH. @maggi373 are you sure this is caused from our side?

**Comment by maggi373** [comment]
> Nothing in that stacktrace references Mekanism and that user is using a heavily modified version of GTNH. @maggi373 are you sure this is caused from our side?

yea, he didnt respond with a new log, so we cant do anything anyway. i did suspect that mek was downloading old version of CCC but it was tested to not matter.
