### ISSUE TITLE
[BUG]: Unable to enter the world.

### ISSUE THREAD

**Issue by LSK-LW** [Thorfusion/Mekanism-Community-Edition#186]
### Describe the bug

Unable to enter world after upgrading from 9.10.37 to 9.10.38

### To Reproduce

1. Upgrading from 9.10.37 to 9.10.38
2. After launching the game, enter the world
3. See error

### Expected behavior

Enter the world normally.

### Mekanism Version

9.10.38

### Minecraft Version is this regarding?

1.7.10

### What OS are you seeing the problem on?

Windows

### Screenshots

![image](https://github.com/user-attachments/assets/2e7a815d-c7ff-4aa1-9c8c-24cf4e89d0d6)

### The crash report in folder ./crash-reports (both server and client logs)

[https://pastebin.com/RDrLGA8v](https://pastebin.com/RDrLGA8v)

**Comment by maggi373** [comment]
fixed by b9c8b44b3910dc70ac16b458351f15519236a1ae
