### ISSUE TITLE
Mekanism loses Redstone Flux on energy transfer.

### ISSUE THREAD

**Issue by DrParadox7** [Thorfusion/Mekanism-Community-Edition#21]
**Describe the bug**
Mekanism machines and generators lose energy when using Thermal Dynamics' Fluxducts.

**To Reproduce**
Get 2 Energy Cubes of the same tier, one full one empty.
Use any Fluxduct to move all the energy from one Energy Cube to another.

**Expected behavior**
_The previously empty Energy becomes full while the other becomes empty._
That does not happen and the energy is lost within this close circuit.

**Screenshots**
![image](https://user-images.githubusercontent.com/47131096/105353246-e9ea8a80-5be6-11eb-9366-6542adacabae.png)
![image](https://user-images.githubusercontent.com/47131096/105353467-2b7b3580-5be7-11eb-85b7-283df11ff6c7.png)
![image](https://user-images.githubusercontent.com/47131096/105354342-55812780-5be8-11eb-9552-7dc53575b4e6.png)

**Version**
Mekanism T.10.6
Forge 10.13.4.1614

**Additional context**
This loss also happens when sending energy straight to TE energy cells from any Mekanism machine, block or multiblock structure.

**Comment by DrParadox7** [comment]
Cause: User Error

**Comment by maggi373** [comment]
might explain what the user error was? since others might find this

**Comment by DrParadox7** [comment]
`D:JoulesToRF=` x  `D:RFToJoules=` ≠ 1

It needs to be **1** or discrepancies happens.

in my case both were 2.5. Setting `RFtoJoules` to 0.4 solved it.

_P.S. You still lose <1 RF each time still but it is negligible_
