### ISSUE TITLE
[BUG] Crash at game starting

### ISSUE THREAD

**Issue by El-Tiagones** [Thorfusion/Mekanism-Community-Edition#24]
**Describe the bug**
The game crashes when tring to launch the game with the mod installed, it may be a compatability issue

Desktop:
 - OS: WIndows 11
 - Modpack: Self made
 - Modpack Version: n/a
 - Mekanism Version: CE 9.10.7
 - Forge Version: 7.10.99.99

Here is a crashlog:
[crash-2021-09-01_12.52.29-client.txt](https://github.com/Thorfusion/Mekanism/files/7092699/crash-2021-09-01_12.52.29-client.txt)

**Comment by maggi373** [comment]
Install codechickenlib and multipart and it should work. 1.7.10 is so old that the links forge use nolonger work to download dependencies

**Comment by maggi373** [comment]
you can get multipart here: https://www.curseforge.com/minecraft/mc-mods/forge-multi-part

**Comment by El-Tiagones** [comment]
> you can get multipart here: https://www.curseforge.com/minecraft/mc-mods/forge-multi-part

Yep, instaling last version of multipart solved it, case closed holmes
