### ISSUE TITLE
[BUG] Enriched Alloy recipe not using the ore dictonary 

### ISSUE THREAD

**Issue by Scipio9001** [Thorfusion/Mekanism-Community-Edition#28]
While you can use other mods steel to craft everything in Mekanism as intended the alloy smelter only takes Mekanism steel instead of anything registered in the ore dictionary as steel.

This was broken with this change.
https://github.com/Thorfusion/Mekanism-1.7.10-Community-Edition/commit/9ec2b2822d7b3dbb7bfc34bdbddba8ba3c5d91f1

It can be fixed easily by replacing MekanismItems.Ingot, 1, 4 with "ingotSteel" used in the rest of the mods crafting recipes so it call on the ore dict and can use other mods steel. 

 - Mekanism Version: 9.10.12

**Comment by maggi373** [comment]
ah, my bad. if you can, make a pull request and you get credit for your work and a cape :)

**Comment by maggi373** [comment]
fixed by #29
