### ISSUE TITLE
Osmium Compressor takes incorrect amount of osmium

### ISSUE THREAD

**Issue by goobyq** [Thorfusion/Mekanism-Community-Edition#32]
When making Refined Obsidian Ingots, the recipe takes 201 Liquid Osmium(1.005 Osmium ingots) so you waste an ingot to complete the craft.

**Comment by maggi373** [comment]
And no other recipe does this?

**Comment by goobyq** [comment]
The refined flowstone ingot might, would have to check

**Comment by maggi373** [comment]
ah, i see whats happening, it does only need 200 but takes one more after its done if you have more osmium available lel
