### ISSUE TITLE
Mekanism + Refined Relocation + Buildcraft looping crash

### ISSUE THREAD

**Issue by IronSpaceCore** [Thorfusion/Mekanism-Community-Edition#33]
There's an issue where, if you take a chest, attach a Mekanism logistical Transporter to it, attach a RR buffer to the Transporter, attach a BC Golden Pipe to the other side of the buffer, and attach a chest to the golden pipe, and put something in the first chest, it causes an entity error that crashes the server every time it's rendered.

 - OS: Windows 10
 - Modpack: The 1.7.10 Pack
 - Modpack Version: v0.10.6
 - Mekanism Version: 9.10.12

This error takes three mods into account, and as such it might be the case that Refined Relocation is moreso to blame than Mekanism, however the error is on Mekanism's side in the crash log.

[lmao.txt](https://github.com/Thorfusion/Mekanism-1.7.10-Community-Edition/files/9498044/lmao.txt)
![cognitohazard](https://user-images.githubusercontent.com/100050106/188665052-24b9948b-ff43-4508-8a3a-8adcfdfac224.png)

Furthermore, there is no reason anyone should ever make a setup like this, but placing an item in the left chest crashes the client to desktop and closes the server, repeatedly, so i figured it was at least worth a shot to report it here.

I'd also like to add that doing this but in reverse, by using a wooden pipe -> buffer -> transporter setup just spits the item out of the buffer, so it's only this direct linear configuration that creates a rendering error

**Comment by maggi373** [comment]
i'm already looking into this and it seems its refined relocations fault. i have so far been unable to compile refined relocation

**Comment by maggi373** [comment]
i was able to reproduce your bug, so im thanking you for the detailed bug report. for those who might wonder how i already knew about this, i found it by accident at xJon/The-1.7.10-Pack#1978

**Comment by IronSpaceCore** [comment]
oh hey that me

(thanks for looking at it, regardless--it's one of thousands of crossmod bugs, and there's no telling from first glance which one is the perpetratror. I'm just glad to see people still care about 1.7 :D )

**Comment by maggi373** [comment]
neither my or drparadox's modpacks have this issue, therefore will not be worked on

**Comment by maggi373** [comment]
we are not supporting other mods than the mods in our modpacks, however i made a quick fix that disables the interaction with the buffer. im not fixing it properly, using such blocks / mods is going the wrong way about it.

**Comment by maggi373** [comment]
@IronSpaceCore this issue has been "fixed", we cant spend time on fixing all mod compat issues, we are focusing on what mods that are in the official packs. this is as good as it gets.
