### ISSUE TITLE
Crash on joining world with v9.10.14

### ISSUE THREAD

**Issue by SisterJacq** [Thorfusion/Mekanism-Community-Edition#34]
Well not hard crash, so much as can't join the world due to an NPE in mekanism.common.Mekanism.serverStarting() (would crash if the error wasn't handled sanely), but same effect of not being able to play. Things worked fine with v9.10.11, so I can revert to that version for now. https://gist.github.com/SisterJacq/112a34e6f3580a618b4a63fbd9d26816

**Comment by maggi373** [comment]
Ah shit, went a little to fast with the latest update. Please try 9.10.12 or 9.10.13. Those should work.

Fixin it tommorrow

**Comment by maggi373** [comment]
What pack are this for, love to see stuff i make in modpacks :)

**Comment by maggi373** [comment]
I see what i did. When I changed so that the voiceserver was by default disabled for security reasons, i forgot to remove the false statement i left at the wrong place. Disabling it in the config would fix the issue. i normally run mekanism with the voiceserver disabled

**Comment by SisterJacq** [comment]
Thanks, I probably should for performance reasons too. And it's just a personal pack for myself.
