### ISSUE TITLE
Question regarding chat message

### ISSUE THREAD

**Issue by xJon** [Thorfusion/Mekanism-Community-Edition#37]
Is there any way to disable the chat message upon joining a world of `[Mekanism] Using developer build x.x`?

**Comment by maggi373** [comment]
Yes, see the config, it was renamed to v2 for users that switched to mekanisn ce and wasnt aware that we support this function. Im gonna rewrite the readme soon and i will include this. 

I can also remotely deactivate it till you update the pack with the new config if needed.

Also a new version is around the corner with fixes for minetweaker and will include #36

The whitelist dim for windmills feature will be added in 9.10.17

PS: remember to turn off the voiceserver in the config, its a security risk and im not supporting it.

**Comment by maggi373** [comment]
Wait, dev build? Uh so its not the update message?. Can you take a screenshot?

**Comment by xJon** [comment]
I disabled `UpdateNotificationsv2` and it doesn't seem to happen anymore :)
For reference, that's how it looked like:
![image](https://user-images.githubusercontent.com/8945347/189792241-4d6dc662-a6ce-49af-b96b-86b69caf8b8b.png)

**Comment by maggi373** [comment]
Ah, its because i havent updated versionnumber at remote

**Comment by maggi373** [comment]
but ye, modpacks should have thhat setting as false regardless
