### ISSUE TITLE
(re)Add the DUMP button on Infusing factories

### ISSUE THREAD

**Issue by Desempregago** [Thorfusion/Mekanism-Community-Edition#39]
![2022-09-18_19 17 40](https://user-images.githubusercontent.com/14002834/190930258-be52e0f4-04c4-4772-9423-68630e7f4e8f.png)

**Comment by maggi373** [comment]
this is not a native feature for mekanism 1.7.10 but we can add it

**Comment by maggi373** [comment]
you can use the pressure gauge and right click on that bar to empty it, does the same with gases, doesnt make sense in this case but it what it is.

**Comment by maggi373** [comment]
is the current ,method of emptying the tank on infusing factory satisfactory or do you still want to add a dump button?

**Comment by Desempregago** [comment]
It isn't needed, but would be nice to have, since the regular infuser has it
