### ISSUE TITLE
[BUG] Industrial Turbine shows 0 RF/t being generated despite energy meter increasing

### ISSUE THREAD

**Issue by Desempregago** [Thorfusion/Mekanism-Community-Edition#40]
![image](https://user-images.githubusercontent.com/14002834/192116430-7f7f6206-b0d9-44f8-bef8-ef1dc081bc25.png)

 - OS: W10
 - Modpack: Custom made, no configs changed
 - Mekanism Version: 9.0.16
 - Forge Version: 10.13.4.1614

**Comment by maggi373** [comment]
does this only happen in rf mode or does it also happen when using mj as measurements in the config file?

**Comment by Desempregago** [comment]
It happens with every energy measurement

**Comment by Desempregago** [comment]
could it be an RF API incompatibility?

**Comment by maggi373** [comment]
dont think so, does this issue happens to other machines aswell or is it isolated to the turbine?

**Comment by Desempregago** [comment]
I only saw it happen to the turbine, might happen with the fusion reactor too. need to confirm.

**Comment by Desempregago** [comment]
Confirmed: It only happens with the turbine.
![2022-10-09_14 42 50](https://user-images.githubusercontent.com/14002834/194771497-71c7985e-6eaf-4018-9ecb-445f11962640.png)

**Comment by Desempregago** [comment]
Also happens with "vanilla" Mekanism.

**Comment by Desempregago** [comment]
so it's most likely a turbine bug that's also present on regular Mekanism

**Comment by maggi373** [comment]
ye

**Comment by maggi373** [comment]
can you provide us a savegame for this bug? would save time in a busy world, as i have never used the turbine before :)

**Comment by Desempregago** [comment]
Will do. As soon as I get home I'll fire up my test instance.

**Comment by maggi373** [comment]
no need to hurry, just askin a good time before actual work on the issue :)

**Comment by Desempregago** [comment]
https://user-images.githubusercontent.com/14002834/202866757-853abe6b-0701-4b6b-bfeb-eb101af1d7c3.mp4


Here's the map (changed the infinite steam source to some Meka ultimate tanks filled with steam)
[testmap.zip](https://github.com/Thorfusion/Mekanism-1.7.10-Community-Edition/files/10047738/test.zip)
