### ISSUE TITLE
[BUG] Drum duplication trough tanks

### ISSUE THREAD

**Issue by SrYthan** [Thorfusion/Mekanism-Community-Edition#49]
**Duplication on fluid tanks**
when filling a fluid tank with any liquid and adding stacked drums (Extra Utilities) in the fluid tank slot, the liquid present in the fluid tank fills all drum

**To Reproduce**
1. place any fluid tank and fill then whith any liquid
2. open the fluid tank and insert a stack of Drum (Extra Utilities)
3. Change mode of Fluid tank to Fill

**Expected behavior**

**Screenshots**

![Screenshot_5](https://user-images.githubusercontent.com/78868186/201154699-fbd09978-1c41-4e40-ac22-0bf8d92c03c6.png)
![Screenshot_6](https://user-images.githubusercontent.com/78868186/201154702-32f3101d-84a3-4fb4-96ba-7d05e4ba15a8.png)
![Screenshot_7](https://user-images.githubusercontent.com/78868186/201154692-47c82425-8dc0-4ccf-918d-98743e2f11e2.png)

**Desktop (please complete the following information):**
 - OS: Win 10
 - Modpack: Custom
 - Modpack Version: Custom
 - Mekanism Version: Latast version

**Please provide the following files**
+ The crash report in folder ./crash-reports (both server and client logs)
+ The full log located in the folder ./logs
+ The configfiles in ./config/mekanism/
+ In special cases where there will be alot of work, also provide the save file where the error occurs.
Use gist.github.com to provide such files.

**Additional context**

**Comment by maggi373** [comment]
I have been able to reproduce this issue, to clarify, putting a stack of drums in the fill port fills each drum in that stack, with the contents of the tank, therefore duplicating it to the amount of tanks in that stack
so you get 64 drums with 14000mb liquid instead of  instead of 1 drum with 14000mb liquid

**Comment by maggi373** [comment]
this also happens with other mods like ender io

**Comment by SrYthan** [comment]
Thank you for the opportunity to report the bug

**Comment by SrYthan** [comment]
If you don't mind, I have some crashes that occur on certain occasions and I would like to report them here, may I?

**Comment by maggi373** [comment]
feel free to create new bug reports :)

**Comment by SrYthan** [comment]
this crash occurred aleatory, i think is a incompatibility with Industrial Upgrade

[Crash.txt](https://github.com/Thorfusion/Mekanism-1.7.10-Community-Edition/files/9983227/Crash.txt)

**Comment by maggi373** [comment]
> this crash occurred aleatory, i think is a incompatibility with Industrial Upgrade
> 
> [Crash.txt](https://github.com/Thorfusion/Mekanism-1.7.10-Community-Edition/files/9983227/Crash.txt)

please create a new issues for new bug reports
