### ISSUE TITLE
[Suggestion] Configure Digital Miner max radius, like in 1.12 and above

### ISSUE THREAD

**Issue by Desempregago** [Thorfusion/Mekanism-Community-Edition#55]
*title explains itself*

**Comment by maggi373** [comment]
nope

**Comment by maggi373** [comment]
already had the idea myself on that but decided against it on increasing max distance.

**Comment by maggi373** [comment]
were you specificly thinking of increasing the max radius of the miner or add a config allowing to set max allowed ranges?

**Comment by Desempregago** [comment]
A config line to set maximum range, as seen in the 1.12+ versions

**Comment by maggi373** [comment]
can do the config thing, but im probably not increasing the max range at 32. i might add comment in the config that 32+ is not supported range as a compromise.

**Comment by Desempregago** [comment]
No need to increase the "vanilla" max range, I just asked for this to add parity to the 1.12 version, where you can set the maximum range up to 128 (IIRC)
