### ISSUE TITLE
[BUG]Place and run Thermoelectric Boiler and Industrial Turbine and right-click to open the GUI, directly causing the client to crash

### ISSUE THREAD

**Issue by Xnidada** [Thorfusion/Mekanism-Community-Edition#56]
**Describe the bug**
Place and run Thermoelectric Boiler and Industrial Turbine and right-click to open the GUI, directly causing the client to crash

**To Reproduce**
1. Place Semol Kertrick Boile Ol, Industrial Rial Turbin,Then run them
2. Connect them
3. Right-clicking them

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
- OS: Win 11
- Modpack: Custom
- Modpack Version: Custom
- Mekanism Version: 9.10.16

**Please provide the following files**
+ The crash report in folder ./crash-reports (both server and client logs)
+ The full log located in the folder ./logs
+ The configfiles in ./config/mekanism/
+ In special cases where there will be alot of work, also provide the save file where the error occurs.
Use gist.github.com to provide such files.
[crash-2022-11-21_12.46.54-client.txt](https://github.com/Thorfusion/Mekanism-1.7.10-Community-Edition/files/10053527/crash-2022-11-21_12.46.54-client.txt)

**Additional context**

**Comment by maggi373** [comment]
please add a screenshot to the bug report

**Comment by DrParadox7** [comment]
@Xnidada 

> Please provide the following files
> 
> - [x] The crash report in folder ./crash-reports (both server and client logs)
> - [ ] The full log located in the folder ./logs
> - [ ] The configfiles in ./config/mekanism/

**Comment by DrParadox7** [comment]
Cannot be replicated on a normal instance with just Mekanism:

![image](https://user-images.githubusercontent.com/47131096/203165180-1ac272ef-3d1d-4607-bc95-bd5231a1156a.png)

Probably not a Mekanism bug. 
It won't be worked on until further evidence is provided.

**Comment by maggi373** [comment]
without any further replies from @Xnidada within 5 days, this issue will be closed.
