### ISSUE TITLE
[BUG]The machine in MOD will not automatically close the GUI when the player is far away from the machine, so that you can brush items

### ISSUE THREAD

**Issue by Xnidada** [Thorfusion/Mekanism-Community-Edition#62]
**Describe the bug**
The machine in MOD will not automatically close the GUI when the player is far away from the machine, so that you can brush items

**To Reproduce**
1. Place any Machine Block and Place items that can move players
2. Put items in GUI
3. Standing on the conveyor belt
4. open gui
5. Wait to move out of the load chunk set by the server
6. Take out items,close gui
7. Run to the machine location and open it
8. See error

**Expected behavior**
Close the GUI when the player is a certain distance from the machine

**Screenshots**
![image](https://user-images.githubusercontent.com/99242646/205433184-f94a2296-59f5-4d91-9d04-63536c3824c7.png)
![image](https://user-images.githubusercontent.com/99242646/205433211-4ebc7f6b-d1a5-4691-b252-0d2019bbb5da.png)
![image](https://user-images.githubusercontent.com/99242646/205433248-b5285b38-9591-492e-ab2d-b2732a0cd22f.png)
![image](https://user-images.githubusercontent.com/99242646/205433264-16024130-2f98-4e81-950a-65eb5f7b91a8.png)
![image](https://user-images.githubusercontent.com/99242646/205433267-116e951e-b8f3-4479-9e2a-23e2f2de90ec.png)

**Desktop (please complete the following information):**
 - OS: server
 - Modpack: any
 - Modpack Version: any
 - Mekanism Version: 9.10.16
Note that we only provide cross-mod support in the official modpacks for this mod. We always offer help and we may fix issues in public packs not on curseforge.

**PROVIDE the following files**
+ The crash report in folder ./crash-reports (both server and client logs)
+ The full log located in the folder ./logs
+ The configfiles in ./config/mekanism/ if edited
+ If the issue is with multiblock structures or similar complex stuff, also provide the save file where the error occurs. So that our time is saved for other bugs instead of trying to copy your build.
Use gist.github.com to provide such files.

https://user-images.githubusercontent.com/99242646/205433355-6604b595-e91f-4d5b-8be9-8e7035ae6617.mp4

Issues not providing the required files will not get help

**Additional context**

**Comment by Xnidada** [comment]
OS: server
Modpack: Custom made, no configs changed
Mekanism Version:  9.10.16
Forge Version: 10.13.4.1614

**Comment by maggi373** [comment]
if i remember correctly this was fixed with another block. but ye, it should throw you out.

**Comment by Xnidada** [comment]
> if i remember correctly this was fixed with another block. but ye, it should throw you out.

No, no, no, no, the tramcar can also let players move. If the GUI is not closed, a bug will appear

**Comment by maggi373** [comment]
I meant throw you out of the gui when out of range, busy day :)

**Comment by Xnidada** [comment]
> I meant throw you out of the gui when out of range, busy day :)

 I meant players can use BUG in the server if not force closing the GUI

**Comment by maggi373** [comment]
Ye, closing the gui. Is there something im missing? Its not doing it now and it should close it when out of "range"

**Comment by Xnidada** [comment]
> Ye, closing the gui. Is there something im missing? Its not doing it now and it should close it when out of "range"

I'm sorry, I didn't understand your meaning before. The English is not so good and hope this bug can be repaired in the next version

**Comment by maggi373** [comment]
you posted the issue Thorfusion#56 you can respond on it to reopen

**Comment by Xnidada** [comment]
> you posted the issue #56 you can respond on it to reopen

I don't know what the problem is. It may be caused by the interaction between ThermalExpansion and MEK
