### ISSUE TITLE
[BUG]When ThermalExpansion ThermalFoundation, CoFHCore Mekanism, CodeChickenCore, CodeChickenLib, ForgeMultipart exist at The same time, The Boiler will get an error

### ISSUE THREAD

**Issue by Xnidada** [Thorfusion/Mekanism-Community-Edition#63]
**Describe the bug**
When ThermalExpansion ThermalFoundation, CoFHCore Mekanism, CodeChickenCore, CodeChickenLib, ForgeMultipart exist at The same time, The Boiler will get an error

**To Reproduce**
1. Download this MOD
2. Place Boiler
3. Waiting or readvance map

**Expected behavior**
Prevents the client from crashing

**Screenshots**
I can't look at him. I can't look at this machine without it crashing.The Modpack and save I will upload at the back

**Desktop (please complete the following information):**
 - OS: win11
- The versions and names of the modpack above : ThermalExpansion-[1.7.10]4.1.5-248,ThermalFoundation-[1.7.10]1.2.6-118,CoFHCore-[1.7.10]3.1.4-329,CodeChickenCore-1.7.10-1.0.7.47-universal,CodeChickenLib-1.7.10-1.1.3.141-universal,ForgeMultipart-1.7.10-1.2.0.347-universal
- Mekanism Version: 9.10.16
Note that we only provide cross-mod support in the official modpacks for this mod. We always offer help and we may fix issues in public packs not on curseforge.

**PROVIDE the following files**
+ crash-reports [crash-2022-12-19_20.39.02-client.txt](https://github.com/Thorfusion/Mekanism-1.7.10-Community-Edition/files/10259328/crash-2022-12-19_20.39.02-client.txt)
+ log [latest.log](https://github.com/Thorfusion/Mekanism-1.7.10-Community-Edition/files/10259334/latest.log)
d
+ save [plotsq.zip](https://github.com/Thorfusion/Mekanism-1.7.10-Community-Edition/files/10259343/plotsq.zip)
+ Modpacks  [mods.zip](https://github.com/Thorfusion/Mekanism-1.7.10-Community-Edition/files/10259359/mods.zip)

Use gist.github.com to provide such files.

Issues not providing the required files will not get help

**Additional context**

**Comment by maggi373** [comment]
File you sent was corrupted for me atleast, might be the japanese in your files that my system might not support, anyway i am pretty certain that this machine works for other players. i however dont use this machine but @DrParadox7 is more experienced with this.

**Comment by Xnidada** [comment]
> File you sent was corrupted for me atleast, might be the japanese in your files that my system might not support, anyway i am pretty certain that this machine works for other players. i however dont use this machine but @DrParadox7 is more experienced with this.

I removed all the other languages in Modpacks ,then it works fine. But if you add for example, buildcraft-7.1.24 or Draconic-Evolution- 1.7.10-1.0.2 or extrautilities-1.2.12 or ImmersiveEngineering-0.7.7(There will actually be more, but that's all I tested), if either one is readded, it will be the original The situation of
+ error-free modpack modpacks 
[mods.zip](https://github.com/Thorfusion/Mekanism-1.7.10-Community-Edition/files/10265870/mods.zip)
+ Adding one of these modpacks doesn't work properly
[errormods.zip](https://github.com/Thorfusion/Mekanism-1.7.10-Community-Edition/files/10265851/errormods.zip)
+ new save  The error position is -97 67 97
[plotsq.zip](https://github.com/Thorfusion/Mekanism-1.7.10-Community-Edition/files/10265864/plotsq.zip)

**Comment by DrParadox7** [comment]
I have all these mods on the [Lost Era Modpack](https://modrinth.com/modpack/the-lost-era) and it does not occur.
If I can't replicate it I can't fix it.

**Comment by maggi373** [comment]
this issue cant be replicated. There are some reasons why the crashing, one is the language, there might be mods that wont work properly with your language.  Second is that you said you were chinese, there might be software stopping modded minecraft working properly, hence the broken world that i checked more closesly yesterday and showed tamper that is in line with such programs. last thing is user error on config/mod/modloader setup. We won't help further unless you manage to recreate the issue on The lost era modpack on modrinth or Terralization modpack on technic (official modpacks). Also provide a video, might help us with what excatly you do. This issue will be closed by new years eve with no reply.

**Comment by maggi373** [comment]
no updates given
