### ISSUE TITLE
Concurrent Modification on Chunkloading

### ISSUE THREAD

**Issue by SrYthan** [Thorfusion/Mekanism-Community-Edition#70]
**Describe the bug**
I don't know the cause, but it happened that an osmium compressor crashed the server when pulling the chunkload event from the mekanism

**To Reproduce**
1. it just happened, no steps to get to the error

**Expected behavior**
When it happened, the player who owned the block was teleporting to another dimension, if that information helps

**Screenshots**
does not have

**Desktop (please complete the following information):**
 - OS: Linux
 - Mekanism Version: Mekanism-1.7.10-Community-Edition-1.7.10-9.10.20

**PROVIDE the following files**
+ The crash report in folder ./crash-reports (both server and client logs)
https://gist.github.com/SrYthan/bdfcdecf323ddbffd447e433c2aac7e3

[crash-2022-12-24_02.16.19-server.txt](https://github.com/Thorfusion/Mekanism-1.7.10-Community-Edition/files/10298040/crash-2022-12-24_02.16.19-server.txt)

**Comment by SrYthan** [comment]
right, it happened when the player teleported and unloaded the location, for some reason it accused a solar panel connected to a basic battery of the mekanism
![Screenshot](https://user-images.githubusercontent.com/78868186/209423387-3cc31d68-d44d-4e12-8ce0-216e780be5ed.png)

**Comment by SrYthan** [comment]
right, what I understand is that applied tried to tick the battery of the mekanism and then the crash occurred trying to load the chunk where the battery was.
I crashed the server 4 times to understand what happened, now I don't know if it's a mekanism error or an applied error...
![Screenshot_1](https://user-images.githubusercontent.com/78868186/209423893-e6785d34-383e-428d-ae51-c061017ca831.png)

**Comment by DrParadox7** [comment]
Concurrent Modification Exception from:
https://github.com/Thorfusion/Mekanism-1.7.10-Community-Edition/blob/28fadd542b66ba4f6946d92799d2c0ce88558e07/src/main/java/mekanism/common/Mekanism.java#L1663
