### ISSUE TITLE
[BUG] Ticking block entity and some blocks has no crafting recipes

### ISSUE THREAD

**Issue by wuyaiii** [Thorfusion/Mekanism-Community-Edition#72]
**Describe the bug**
1、Place Bio-Generator server crash
Mekanism Version:9.10.21 will crash
Mekanism Version:9.10.20 works fine

2、Solar Neutron Activator,Resistive Heater,Quantum Entangloporter and other blocks has no crafting recipes
Mekanism Version:9.10.21 No recipe
Mekanism Version:9.10.20 have recipe

**To Reproduce**

1.Place the Bio-Generator 
2.check the server crash log

**Expected behavior**
Get Bio-Generator to work without crashing the server
Fixed recipes for Solar Neutron Activator , Resistive Heater and other blocks

**Screenshots**
Unable to take a screenshot at the moment of the crash

**Desktop (please complete the following information):**
 - OS: win10
 - Modpack:Tested on both single-player client and server with only MEK installed
 - Modpack Version:CodeChickenLib-1.7.10-1.1.3.141-universal,ForgeMultipart-1.7.10-1.2.0.347-universal
 - Mekanism Version:9.10.21
Note that we only provide cross-mod support in the official modpacks for this mod. We always offer help and we may fix issues in public packs not on curseforge.

**PROVIDE the following files**
crash-reports [crash-2022-12-27_15.01.09-server.txt](https://github.com/Thorfusion/Mekanism-1.7.10-Community-Edition/files/10306788/crash-2022-12-27_15.01.09-server.txt)
log [latest.log](https://github.com/Thorfusion/Mekanism-1.7.10-Community-Edition/files/10306791/latest.log)

Issues not providing the required files will not get help

**Additional context**

**Comment by maggi373** [comment]
pleaser create two different bug reports

**Comment by maggi373** [comment]
fixed
