### ISSUE TITLE
[BUG]: crash report

### ISSUE THREAD

**Issue by LSK-LW** [Thorfusion/Mekanism-Community-Edition#77]
### Describe the bug

I don't know why the game won't start with the IC2.

### Expected behavior

Start the game normally.

### Mekanism Version

9.10.23-ALL

### Minecraft Version is this regarding?

1.7.10

### What OS are you seeing the problem on?

Windows

### Screenshots

![image](https://user-images.githubusercontent.com/12579533/212541321-88e102ad-c8b8-41e8-9b1d-2dd668e1ae71.png)

### The crash report in folder ./crash-reports (both server and client logs)
crash-2023-01-15_20.46.39-client.txt : [https://pastebin.com/qCr6SWw8](https://pastebin.com/qCr6SWw8)
### Please provide the following other files
Use default configuration file.

latest.txt : [https://pastebin.com/qFmSRLTV](https://pastebin.com/qFmSRLTV)

**Comment by maggi373** [comment]
please fill out the form as described, will be closed by two days.

**Comment by LSK-LW** [comment]
> please fill out the form as described, will be closed by two days.

please check again

**Comment by maggi373** [comment]
when creating a bug report when it says please provide the following files, its asking you to use gist or pastebin. also, we need the config which it also states.

**Comment by maggi373** [comment]
check if its crashing with default config files

**Comment by maggi373** [comment]
also, crash-report should be pasted. next time ACTUALLY read the form and do what it says

**Comment by LSK-LW** [comment]
> when creating a bug report when it says please provide the following files, its asking you to use gist or pastebin. also, we need the config which it also states.

The crash occurs with the default configuration,It has been corrected again, using pastebin.

**Comment by LSK-LW** [comment]
> also, crash-report should be pasted. next time ACTUALLY read the form and do what it says

Sorry, my English is limited and I can't fully understand the requirements in the form. These questions will not appear next time.

**Comment by maggi373** [comment]
was about to close this issue, due to how many issues mek has with chinese computers, but this is an actual issue, both official packs and many others have ic2 and they havent had issues

**Comment by maggi373** [comment]
> > also, crash-report should be pasted. next time ACTUALLY read the form and do what it says
> 
> Sorry, my English is limited and I can't fully understand the requirements in the form. These questions will not appear next time.

most people know english pretty good today but there are exeptions ofc, so i'm sorry if i was a bit harsh. i'm a bit tired of young people not bothered to read the whole form/texts today.

**Comment by maggi373** [comment]
https://github.com/Thorfusion/Mekanism-1.7.10-Community-Edition/blob/24954205fd051e1236474a6137c98760f3be172e/src/main/java/mekanism/common/integration/OreDictManager.java#L71

**Comment by maggi373** [comment]
testing a fix now

**Comment by LSK-LW** [comment]
> testing a fix now

Thanks for your fix, the test worked successfully.
