### ISSUE TITLE
[ENHANCEMENT]: Cardboard box config option or stackable

### ISSUE THREAD

**Issue by AstroTibs** [Thorfusion/Mekanism-Community-Edition#79]
### Is your enhancement request related to a problem? Please describe.

I thought single-use cardboard boxes were a bug until I tried multiple versions and narrowed it down to 9.10.16, where it was in the changelog.

### Describe the solution you'd like

I'd like:

1. A config option for whether cardboard boxes are single use
2. An increased stack limit for the empty boxes (possibly as a config boolean, or even `int` for stack size limit)

### Describe alternatives you've considered

I could roll back to v9.10.15, but I'd be sacrificing current and future updates and features, and would have to re-format my configs back to the old version again.

### Minecraft Version is this regarding?

1.7.10

### Additional context

Cardboard Box is my modpack's go-to move-stuff block. Being suddenly very limited in how it's used will impact my server.

It is especially useful as for moving tile entities around (especially Bibliocraft's Labels and Fancy Signs) in case you're doing decorating or remodeling.

I am not opposed to single-use, but then having to dedicate a whole slot to only one box is annoying. It would be better to have a stack of some size to speed up moving or redecorating.

There are other ways in my pack to carry more stuff, but the cardboard box is the only way to relocate blocks that are otherwise extremely tedious to tear down and set back up.

**Comment by maggi373** [comment]
only adding the config option

**Comment by maggi373** [comment]
feel free to add a stackable feature yourself and make a pull request, but it probably will be susceptible to dupes
